# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            'Estevan A. Dixon'
tagline:          'is awesome'
description:      A Journalisam and Mass Communications student at the University of Iowa with a bright future ahead of him in Advertising
url:              http://edixn.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      'theme-base-0c'
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Estevan Dixon'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1
